version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: b2b-marketplace-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: b2b-marketplace
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - b2b-network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: b2b-marketplace-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - b2b-network

volumes:
  mongodb_data:

networks:
  b2b-network:
    driver: bridge 